In [1]:
pip install pandas

Requirement already satisfied: pandas in .\radhe\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in .\radhe\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\radhe\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\radhe\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\radhe\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Used_Bikes.csv')

In [4]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [5]:
df.info()#informacen nikalne ke liye

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [6]:
df.columns #features

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [7]:
df.bike_name#kisi column ko nikalne ke liye

0          TVS Star City Plus Dual Tone 110cc
1                 Royal Enfield Classic 350cc
2                        Triumph Daytona 675R
3                        TVS Apache RTR 180cc
4        Yamaha FZ S V 2.0 150cc-Ltd. Edition
                         ...
32643                  Hero Passion Pro 100cc
32644                    TVS Apache RTR 180cc
32645                Bajaj Avenger Street 220
32646               Hero Super Splendor 125cc
32647                      Bajaj Pulsar 150cc
Name: bike_name, Length: 32648, dtype: str

In [8]:
df.city#particular column ke liye

0        Ahmedabad
1            Delhi
2            Delhi
3        Bangalore
4        Bangalore
           ...
32643        Delhi
32644       Karnal
32645        Delhi
32646       Jaipur
32647         Pune
Name: city, Length: 32648, dtype: str

In [9]:
df['brand']#particular way official tarika sahi tarika ye bhi nahi h

0                  TVS
1        Royal Enfield
2              Triumph
3                  TVS
4               Yamaha
             ...
32643             Hero
32644              TVS
32645            Bajaj
32646             Hero
32647            Bajaj
Name: brand, Length: 32648, dtype: str

In [10]:
df[['owner']]#particular column ko dekhne ke liye sahi tarika

             owner
0      First Owner
1      First Owner
2      First Owner
3      First Owner
4      First Owner
...            ...
32643  First Owner
32644  First Owner
32645  First Owner
32646  First Owner
32647  First Owner

[32648 rows x 1 columns]

In [11]:
df[['power']]# same h upper ki tarah hi

       power
0      110.0
1      350.0
2      675.0
3      180.0
4      150.0
...      ...
32643  100.0
32644  180.0
32645  220.0
32646  125.0
32647  150.0

[32648 rows x 1 columns]

In [12]:
df.head()#upper ki 5 value nikalne ke liye

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [13]:
df.head(10) # 10 nikalne ke liye

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [14]:
df.tail()#niche se 5 value deta h bydefault

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [15]:
df.tail(12)# 12 records (row)of bottom

,bike_name,price,city,kms_driven,owner,age,power,brand
32636,KTM RC 390cc,196700.0,Mumbai,13216.0,First Owner,4.0,390.0,KTM
32637,Bajaj Pulsar 150cc,25000.0,Delhi,32588.0,First Owner,9.0,150.0,Bajaj
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [16]:
df.duplicated()#duplicate value count karne ke liye

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [17]:
df.duplicated().sum()#duplicate value ke sum ke liye

np.int64(25324)

In [18]:
df.drop_duplicates()#duplicate value ko drop karne ke liye

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [19]:
df.duplicated().sum()

np.int64(25324)

In [20]:
df.drop_duplicates(inplace=True)#parameter origanal deta ko delete kar deta hai

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.isnull()# null value check karne ke liye

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [23]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [24]:
#null value ko drop karne ke lie
df.dropna(inplace=True)

In [25]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [26]:
#kisi column ki uniqe value nikalne ke liye
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [27]:
df['owner'].nunique()#number of uniqe value ko count kar ke deta h

4

In [28]:
df[['brand']].nunique()

brand    23
dtype: int64

In [29]:
df['city'].unique()#city ki uniqe value ke liye

<StringArray>
[   'Ahmedabad',        'Delhi',    'Bangalore',       'Mumbai',
       'Kalyan',    'Faridabad',       'Mettur',    'Hyderabad',
      'Kaithal',      'Gurgaon',
 ...
  'Bhubaneswar',      'Raiganj', 'Bhilai Nagar',       'Baloda',
     'Anantnag',   'Berhampore',      'Silvasa',       'Hospet',
        'Palai',        'Sidhi']
Length: 443, dtype: str

In [30]:
df['brand'].value_counts()#ye value count kar deta h uniqe value ki

brand
Bajaj              2081
Royal Enfield      1346
Hero               1142
Honda               676
Yamaha              651
TVS                 481
KTM                 375
Suzuki              203
Harley-Davidson      91
Kawasaki             61
Hyosung              53
Mahindra             50
Benelli              46
Triumph              21
Ducati               20
BMW                  10
Jawa                  7
Indian                3
MV                    3
Rajdoot               1
LML                   1
Yezdi                 1
Ideal                 1
Name: count, dtype: int64

In [31]:
# df.drop('city',axis=1,inplace=True)# kisi ak column ko drop karne ke liye

In [32]:
# df

In [33]:
#2 column ko drop karne ke liye
df.drop(['city','bike_name'], axis=1, inplace=True)

In [34]:
df

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [35]:
char=df.select_dtypes(include="object")#data type ko select karne ke liye select_dtypes
# include="object" iska matlab h ki ye usi ko select karega jiska funtion objjective h

C:\Users\HP\AppData\Local\Temp\ipykernel_18032\1501640753.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  char=df.select_dtypes(include="object")#data type ko select karne ke liye select_dtypes

In [36]:
char

            owner            brand
0     First Owner              TVS
1     First Owner    Royal Enfield
2     First Owner          Triumph
3     First Owner              TVS
4     First Owner           Yamaha
...           ...              ...
9362  First Owner             Hero
9369  First Owner            Bajaj
9370  First Owner  Harley-Davidson
9371  First Owner            Bajaj
9372  First Owner            Bajaj

[7324 rows x 2 columns]

In [37]:
iint=df.select_dtypes(exclude='object')

In [38]:
iint

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [39]:
iint=df.select_dtypes(exclude='O')#ye integer data type ke colums ko hi select karta h

In [40]:
iint

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [41]:
df

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [42]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [43]:
# df[df['brand']=='Royal Enfield']#query find out karna

In [44]:
# df['owner'].unique()

In [45]:
# Bullet=df[df['brand']=='Royal Enfield']

In [46]:
# Bullet2=Bullet[Bullet['owner']=='First Owner']

In [47]:
# Bullet2[Bullet2['age']<2]

In [48]:
df

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [49]:
# df[([df['brand']=='Hero']) & (df['owner']=='First Owner') & (df['age'<=2]) & (df['kms_driven']<=50000)]

In [50]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [51]:
owner_dict={
    'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4
}

In [52]:
df['owner']=df['owner'].map(owner_dict)

In [53]:
df

         price  kms_driven  owner  age  power            brand
0      35000.0     17654.0      1  3.0  110.0              TVS
1     119900.0     11000.0      1  4.0  350.0    Royal Enfield
2     600000.0       110.0      1  8.0  675.0          Triumph
3      65000.0     16329.0      1  4.0  180.0              TVS
4      80000.0     10000.0      1  3.0  150.0           Yamaha
...        ...         ...    ...  ...    ...              ...
9362   25000.0     48587.0      1  8.0  150.0             Hero
9369   35000.0     60000.0      1  9.0  220.0            Bajaj
9370  450000.0      3430.0      1  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0      1  4.0  400.0            Bajaj
9372   80000.0      7127.0      1  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [54]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [55]:
brand_dict={  'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23

}
df['brand']=df['brand'].map(brand_dict) # map ka use number assign karne ke liye hota hai
#encoding kaarne ke liye use hota h map function ka

In [56]:
df

         price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0      1
1     119900.0     11000.0      1  4.0  350.0      2
2     600000.0       110.0      1  8.0  675.0      3
3      65000.0     16329.0      1  4.0  180.0      1
4      80000.0     10000.0      1  3.0  150.0      4
...        ...         ...    ...  ...    ...    ...
9362   25000.0     48587.0      1  8.0  150.0      6
9369   35000.0     60000.0      1  9.0  220.0      7
9370  450000.0      3430.0      1  4.0  750.0     15
9371  139000.0     21300.0      1  4.0  400.0      7
9372   80000.0      7127.0      1  5.0  220.0      7

[7324 rows x 6 columns]

In [57]:
df.rename(columns={'age':'model'})#column rename karne ke liye

         price  kms_driven  owner  model  power  brand
0      35000.0     17654.0      1    3.0  110.0      1
1     119900.0     11000.0      1    4.0  350.0      2
2     600000.0       110.0      1    8.0  675.0      3
3      65000.0     16329.0      1    4.0  180.0      1
4      80000.0     10000.0      1    3.0  150.0      4
...        ...         ...    ...    ...    ...    ...
9362   25000.0     48587.0      1    8.0  150.0      6
9369   35000.0     60000.0      1    9.0  220.0      7
9370  450000.0      3430.0      1    4.0  750.0     15
9371  139000.0     21300.0      1    4.0  400.0      7
9372   80000.0      7127.0      1    5.0  220.0      7

[7324 rows x 6 columns]

In [58]:
x=df.drop('price',axis=1)

In [59]:
x

      kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      1
1        11000.0      1  4.0  350.0      2
2          110.0      1  8.0  675.0      3
3        16329.0      1  4.0  180.0      1
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
9362     48587.0      1  8.0  150.0      6
9369     60000.0      1  9.0  220.0      7
9370      3430.0      1  4.0  750.0     15
9371     21300.0      1  4.0  400.0      7
9372      7127.0      1  5.0  220.0      7

[7324 rows x 5 columns]

In [60]:
y=df[['price']]

In [61]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [62]:
df.isnull().sum()

price         0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [63]:
x

      kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      1
1        11000.0      1  4.0  350.0      2
2          110.0      1  8.0  675.0      3
3        16329.0      1  4.0  180.0      1
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
9362     48587.0      1  8.0  150.0      6
9369     60000.0      1  9.0  220.0      7
9370      3430.0      1  4.0  750.0     15
9371     21300.0      1  4.0  400.0      7
9372      7127.0      1  5.0  220.0      7

[7324 rows x 5 columns]

In [64]:
#df.to_csv("clean bike.csv")#file save ke liye

In [65]:
! pip install scikit-learn

Requirement already satisfied: scikit-learn in .\radhe\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in .\radhe\Lib\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in .\radhe\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in .\radhe\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in .\radhe\Lib\site-packages (from scikit-learn) (3.6.0)

In [66]:
import sklearn as sns

In [67]:
#sklearn.model_selection-algo select karta h
# train_test_split=data ko 2 bhag me baat deta h jisse accusecy ckeck ho sake
# 80 or 20 ka validation split hota h train and test

from sklearn.model_selection import train_test_split
x_train ,x_test, y_train , y_test=train_test_split(x, y, test_size=0.2,random_state=42)

In [68]:
#shape row and column ko batata hai
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(5859, 5) (1465, 5) (5859, 1) (1465, 1)

In [69]:
#model ko train karne ke liye
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [70]:
lr.fit(x_train,y_train)
#model ko data dene ke kaam aata h

LinearRegression()

In [71]:
x_test

      kms_driven  owner   age  power  brand
4909     22500.0      1   6.0  350.0      2
1942      3198.0      1   5.0  500.0      2
5763     15000.0      1   6.0  220.0      7
4800     27000.0      1  12.0  150.0      4
7614     16764.0      1   9.0  100.0      6
...          ...    ...   ...    ...    ...
5653     16523.0      1   5.0  750.0     15
609       2881.0      1   7.0  250.0     14
4211     23833.0      1   4.0  150.0      8
6379      9282.0      1   7.0  500.0      2
647       2980.0      1   6.0  160.0      1

[1465 rows x 5 columns]

In [72]:
#predict 
pred =lr.predict(x_test)

In [73]:
honda_bike=[[17654.0,	1,	3.0	,110.0,	1]]

In [ ]:
lst=[[16764.0,	1,	9.0,	100.0,	6]]

In [ ]:

# check karega hota h kitna predict karna
lr.predict(lst)

d:\Data science\Flask\Bike-price-prediction\radhe\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[8532.57704594]])

In [ ]:
lr.predict(honda_bike)

d:\Data science\Flask\Bike-price-prediction\radhe\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[-10040.71874744]])

In [77]:
pred

array([[125382.54523531],
       [216422.20333617],
       [ 96966.48595241],
       ...,
       [ 72233.83615101],
       [208856.67620686],
       [  9305.60087569]], shape=(1465, 1))

In [78]:
y_test

         price
4909   88400.0
1942  102850.0
5763   67000.0
4800   30000.0
7614   20000.0
...        ...
5653  395000.0
609   140000.0
4211   54500.0
6379  114000.0
647    36000.0

[1465 rows x 1 columns]

In [ ]:
#
# from sklearn.ensemble import RandomForestRegressor
# rfg=RandomForestRegressor()

In [ ]:

# rfg.fit(x_train,y_train)

d:\Data science\Flask\Bike-price-prediction\radhe\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [82]:
import joblib

In [83]:
joblib.dump(lr,"liner_model.lb")

['liner_model.lb']

In [84]:
model=joblib.load('liner_model.lb')

In [85]:
model=joblib.load('liner_model.lb')

In [86]:
model.predict(x_test)

array([[125382.54523531],
       [216422.20333617],
       [ 96966.48595241],
       ...,
       [ 72233.83615101],
       [208856.67620686],
       [  9305.60087569]], shape=(1465, 1))